import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@fortawesome/fontawesome-free/css/all.min.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import React, { Suspense } from "react";
import Footer from "../lib/components/landing-page/footer/footer";
import { RefineContext } from "./_refine_context";
import "./globals.css";

const getstInter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fresh Food",
  description: "Generated by create refine app",
  icons: {
    icon: "/icon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies();
  const theme = cookieStore.get("theme");

  return (
    <html lang="en" className={getstInter.className}>
      <body className="antialiased">
        <Suspense >
          <AntdRegistry>
            <RefineContext defaultMode={theme?.value}>
              <main className="">{children}</main>
              <Footer />
            </RefineContext>
          </AntdRegistry>
        </Suspense>
      </body>
    </html>
  );
}
