import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@fortawesome/fontawesome-free/css/all.min.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import React, { Suspense } from "react";
import { Toaster } from "react-hot-toast";
import { RefineContext } from "./_refine_context";
import "./globals.css";
import { CartProvider } from "../contexts/cart-context";
import { AddressProvider } from "../contexts/address-context";

const getstInter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fresh Food",
  description: "Generated by create refine app",
  icons: {
    icon: "/icon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme");

  return (
    <html lang="en" className={getstInter.className} suppressHydrationWarning>
      <body className="antialiased" suppressHydrationWarning>
        <Suspense>
          <AntdRegistry>
            <RefineContext defaultMode={theme?.value}>
              <CartProvider>
                <AddressProvider>
                  <main className="min-h-screen">{children}</main>
                  <Toaster
                    position="top-center"
                    toastOptions={{
                      duration: 2000,
                      style: {
                        background: '#363636',
                        color: '#fff',
                        fontSize: '14px',
                        borderRadius: '10px',
                        padding: '12px 20px',
                      },
                      success: {
                        duration: 2000,
                        iconTheme: {
                          primary: '#10b981',
                          secondary: '#fff',
                        },
                      },
                      error: {
                        duration: 2000,
                        iconTheme: {
                          primary: '#ef4444',
                          secondary: '#fff',
                        },
                      },
                    }}
                  />
                </AddressProvider>
              </CartProvider>
            </RefineContext>
          </AntdRegistry>
        </Suspense>
      </body>
    </html>
  );
}
